"""empty message

Revision ID: 093bc85e3096
Revises: 
Create Date: 2021-06-23 23:57:50.990265

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '093bc85e3096'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('last_name', sa.String(length=80), nullable=False),
    sa.Column('phone', sa.String(length=16), nullable=False),
    sa.Column('salt', sa.String(length=40), nullable=False),
    sa.Column('hashed_password', sa.String(length=240), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('real_state_agency',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company', sa.String(length=30), nullable=False),
    sa.Column('description', sa.String(length=900), nullable=False),
    sa.Column('location', sa.String(length=20), nullable=False),
    sa.Column('team_agents', sa.Integer(), nullable=False),
    sa.Column('listings', sa.Integer(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company'),
    sa.UniqueConstraint('description'),
    sa.UniqueConstraint('listings'),
    sa.UniqueConstraint('location')
    )
    op.create_table('realstate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('total_area', sa.Integer(), nullable=True),
    sa.Column('builded_surface', sa.Integer(), nullable=True),
    sa.Column('rooms', sa.Integer(), nullable=True),
    sa.Column('bathrooms', sa.Integer(), nullable=True),
    sa.Column('parkings', sa.Integer(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('contact_phone', sa.Integer(), nullable=True),
    sa.Column('contact_rrss', sa.String(length=50), nullable=True),
    sa.Column('type_transaction', sa.String(length=50), nullable=True),
    sa.Column('additional_information', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contact_phone')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('last_name', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('id_document', sa.Integer(), nullable=False),
    sa.Column('salt', sa.String(length=40), nullable=False),
    sa.Column('hashed_password', sa.String(length=240), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('id_document')
    )
    op.create_table('transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('id_realState', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_realState'], ['realstate.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transaction')
    op.drop_table('user')
    op.drop_table('realstate')
    op.drop_table('real_state_agency')
    op.drop_table('agent')
    # ### end Alembic commands ###
