"""empty message

Revision ID: 271c7d98e0a3
Revises: 
Create Date: 2021-06-24 23:15:23.159011

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '271c7d98e0a3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent', sa.Column('city', sa.String(length=400), nullable=True))
    op.add_column('realstate', sa.Column('city', sa.String(length=100), nullable=True))
    op.add_column('realstate', sa.Column('address', sa.String(length=500), nullable=True))
    op.add_column('realstate', sa.Column('price', sa.Integer(), nullable=True))
    op.add_column('realstate', sa.Column('contact_phone', sa.Integer(), nullable=True))
    op.add_column('realstate', sa.Column('contact_rrss', sa.String(length=50), nullable=True))
    op.add_column('realstate', sa.Column('type_transaction', sa.String(length=50), nullable=True))
    op.add_column('realstate', sa.Column('additional_information', sa.String(length=200), nullable=True))
    op.add_column('realstate', sa.Column('image', sa.String(length=500), nullable=True))
    op.create_unique_constraint(None, 'realstate', ['contact_phone'])
    op.create_unique_constraint(None, 'realstate', ['image'])
    op.drop_column('realstate', 'location')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('realstate', sa.Column('location', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'realstate', type_='unique')
    op.drop_constraint(None, 'realstate', type_='unique')
    op.drop_column('realstate', 'image')
    op.drop_column('realstate', 'additional_information')
    op.drop_column('realstate', 'type_transaction')
    op.drop_column('realstate', 'contact_rrss')
    op.drop_column('realstate', 'contact_phone')
    op.drop_column('realstate', 'price')
    op.drop_column('realstate', 'address')
    op.drop_column('realstate', 'city')
    op.drop_column('agent', 'city')
    # ### end Alembic commands ###
