"""empty message

Revision ID: 3319d5177e8d
Revises: 92f70b6170cd
Create Date: 2021-06-15 19:59:13.328387

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3319d5177e8d'
down_revision = '92f70b6170cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('real_state_agency',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company', sa.String(length=30), nullable=False),
    sa.Column('description', sa.String(length=900), nullable=False),
    sa.Column('location', sa.String(length=20), nullable=False),
    sa.Column('team_agents', sa.Integer(), nullable=False),
    sa.Column('listings', sa.Integer(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company'),
    sa.UniqueConstraint('description'),
    sa.UniqueConstraint('listings'),
    sa.UniqueConstraint('location')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('real_state_agency')
    # ### end Alembic commands ###
