"""empty message

Revision ID: 43ace1e5021e
Revises: d6f56f5d7e21
Create Date: 2021-06-20 20:15:11.654415

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43ace1e5021e'
down_revision = 'd6f56f5d7e21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('realstate_id_transaction_fkey', 'realstate', type_='foreignkey')
    op.drop_column('realstate', 'id_transaction')
    op.add_column('transaction', sa.Column('id_realState', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'transaction', 'realstate', ['id_realState'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transaction', type_='foreignkey')
    op.drop_column('transaction', 'id_realState')
    op.add_column('realstate', sa.Column('id_transaction', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('realstate_id_transaction_fkey', 'realstate', 'transaction', ['id_transaction'], ['id'])
    # ### end Alembic commands ###
