"""empty message

Revision ID: 5499b171f974
Revises: 
Create Date: 2021-06-18 21:19:52.883135

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5499b171f974'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('real_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('location', sa.String(length=500), nullable=True),
    sa.Column('total_area', sa.Integer(), nullable=True),
    sa.Column('builded_surface', sa.Integer(), nullable=True),
    sa.Column('rooms', sa.Integer(), nullable=True),
    sa.Column('bathrooms', sa.Integer(), nullable=True),
    sa.Column('parkings', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('agent', sa.Column('description', sa.String(length=200), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agent', 'description')
    op.drop_table('real_state')
    # ### end Alembic commands ###
