"""empty message

Revision ID: e95f4aead0c0
Revises: 
Create Date: 2021-06-21 23:49:20.901171

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e95f4aead0c0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('last_name', sa.String(length=80), nullable=False),
    sa.Column('phone', sa.String(length=16), nullable=False),
    sa.Column('salt', sa.String(length=40), nullable=False),
    sa.Column('hashed_password', sa.String(length=240), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('real_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('location', sa.String(length=500), nullable=True),
    sa.Column('total_area', sa.Integer(), nullable=True),
    sa.Column('builded_surface', sa.Integer(), nullable=True),
    sa.Column('rooms', sa.Integer(), nullable=True),
    sa.Column('bathrooms', sa.Integer(), nullable=True),
    sa.Column('parkings', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('last_name', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('id_document', sa.Integer(), nullable=False),
    sa.Column('salt', sa.String(length=40), nullable=False),
    sa.Column('hashed_password', sa.String(length=240), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('id_document')
    )
    op.create_table('real_state_agent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_agent', sa.Integer(), nullable=True),
    sa.Column('id_RealState', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_RealState'], ['real_state.id'], ),
    sa.ForeignKeyConstraint(['id_agent'], ['agent.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('real_state_agent')
    op.drop_table('user')
    op.drop_table('real_state')
    op.drop_table('agent')
    # ### end Alembic commands ###
