"""empty message

Revision ID: ed7aea3b93b3
Revises: c74ebfe9c6c3
Create Date: 2021-06-24 14:40:44.347803

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed7aea3b93b3'
down_revision = 'c74ebfe9c6c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('realstate', sa.Column('image', sa.String(length=500), nullable=True))
    op.create_unique_constraint(None, 'realstate', ['image'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'realstate', type_='unique')
    op.drop_column('realstate', 'image')
    # ### end Alembic commands ###
