"""empty message

Revision ID: f77e6cd73825
Revises: 87ff07e361e5
Create Date: 2021-06-24 22:44:38.238289

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f77e6cd73825'
down_revision = '87ff07e361e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent', sa.Column('location', sa.String(length=80), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agent', 'location')
    # ### end Alembic commands ###
